# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    thing1_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    thing2_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    thing1_gripper_controller:
      type: position_controllers/GripperActionController


    thing2_gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

thing1_controller:
  ros__parameters:
    joints:
      - thing1_shoulder_pan_joint
      - thing1_shoulder_lift_joint
      - thing1_elbow_joint
      - thing1_wrist_1_joint
      - thing1_wrist_2_joint
      - thing1_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
thing2_controller:
  ros__parameters:
    joints:
      - thing2_shoulder_pan_joint
      - thing2_shoulder_lift_joint
      - thing2_elbow_joint
      - thing2_wrist_1_joint
      - thing2_wrist_2_joint
      - thing2_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
thing1_gripper_controller:
  ros__parameters:
    joint: thing1_robotiq_85_left_knuckle_joint
thing2_gripper_controller:
  ros__parameters:
    joint: thing2_robotiq_85_left_knuckle_joint
